#!/bin/bash
DOTFILES_DIR=~/dotfiles

# i3 general configuration
echo "Creating symlink for i3 config..."
mkdir -p ~/.config/i3
ln -sf $DOTFILES_DIR/i3/config ~/.config/i3/config
echo "Symlink created: ~/.config/i3/config -> $DOTFILES_DIR/i3/config"

# i3 lock configuration
echo "Creating symlink for lock custom script..."
chmod +x $DOTFILES_DIR/i3/lock-script
ln -sf $DOTFILES_DIR/i3/lock-script ~/.config/i3/lock-script
echo "Symlink created: ~/.config/i3/lock-script -> $DOTFILES_DIR/i3/lock-script"

# i3status configuration
echo "Creating symlink for i3status config..."
sudo ln -sf $DOTFILES_DIR/i3/i3status.conf /etc/i3status.conf
echo "Symlink created: /etc/i3status.conf -> $DOTFILES_DIR/i3/i3status.conf"

# volulme keys configuration (ThinkBook)
echo "Creating symlink for volume keys config..."
sudo mkdir -p /etc/acpi/events/
sudo ln -sf $DOTFILES_DIR/acpi/events/volume_keys /etc/acpi/events/volume_keys
echo "Symlink created: /etc/acpi/events/volume_keys -> $DOTFILES_DIR/acpi/events/volume_keys"
echo "Restarting ACPI daemon..."
sudo systemctl restart acpid
echo "ACPI daemon restarted successfully."

#  .bashrc
echo "Creating symlink for .bashrc..."
ln -sf $DOTFILES_DIR/.bashrc ~/.bashrc
echo "Symlink created: ~/.bashrc -> $DOTFILES_DIR/.bashrc"
echo "Reloading .bashrc..."
source ~/.bashrc
echo ".bashrc reloaded successfully."
